# Generated by Django 2.2 on 2019-04-28 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория товаров',
                'verbose_name_plural': 'категории товаров',
            },
        ),
        migrations.CreateModel(
            name='GoodСharacteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255, unique=True, verbose_name='название')),
                ('value', models.TextField(blank=True, verbose_name='описание')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Good', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'характеристика товара',
                'verbose_name_plural': 'характеристики товара',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.GoodsCategory', verbose_name='категория'),
        ),
    ]
