# Generated by Django 2.2 on 2019-05-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190429_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodсharacteristic',
            name='caption',
            field=models.CharField(max_length=255, verbose_name='название'),
        ),
    ]
